"""initial schema

Revision ID: 83b27cf3a645
Revises: 
Create Date: 2026-04-26 20:22:25.938951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83b27cf3a645'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_category', sa.Enum('chest', 'back', 'legs', 'core', 'arms', 'shoulders', 'cardio', name='bodycategory'), nullable=False),
    sa.Column('equipment', sa.Enum('bar', 'dumbbell', 'machine', 'cable', 'free-weight', name='equipment'), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    op.create_table('plan',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('duration_type', sa.Enum('days', 'weeks', 'months', 'years', name='durationtype'), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workout_days_per_week', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_title'), 'plan', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('weekly_workout_plan',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_day',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weekly_plan_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_rest', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.CheckConstraint('(weekly_plan_id IS NOT NULL AND plan_id IS NULL) OR (weekly_plan_id IS NULL AND plan_id IS NOT NULL)', name='plan_day_exactly_one_parent'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_workout_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_day_plan_id'), 'plan_day', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_day_weekly_plan_id'), 'plan_day', ['weekly_plan_id'], unique=False)
    op.create_table('user_plan_assignment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('in-progress', 'completed', 'cancelled', 'paused', name='user_plan_assignment_status'), nullable=False),
    sa.Column('remaining_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_plan_assignment_plan_id'), 'user_plan_assignment', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_plan_assignment_user_id'), 'user_plan_assignment', ['user_id'], unique=False)
    op.create_index('uq_one_active_assignment_per_user', 'user_plan_assignment', ['user_id'], unique=True, postgresql_where=sa.text("status IN ('in-progress')"))
    op.create_table('weekly_workout_plan_assignment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weekly_plan_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('week_frequency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_workout_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_workout_plan_assignment_plan_id'), 'weekly_workout_plan_assignment', ['plan_id'], unique=False)
    op.create_index(op.f('ix_weekly_workout_plan_assignment_weekly_plan_id'), 'weekly_workout_plan_assignment', ['weekly_plan_id'], unique=False)
    op.create_table('exercise_assignment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_day_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=True),
    sa.Column('exercise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_assignment_exercise_id'), 'exercise_assignment', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_assignment_plan_day_id'), 'exercise_assignment', ['plan_day_id'], unique=False)
    op.create_table('workout_attendance',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_plan_assignment_id', sa.String(), nullable=False),
    sa.Column('plan_day_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('attended', 'absent', 'injured', 'sick', name='attendancestatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_day_id'], ['plan_day.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_plan_assignment_id'], ['user_plan_assignment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_plan_assignment_id', 'date', name='uq_attendance_per_day')
    )
    op.create_index(op.f('ix_workout_attendance_plan_day_id'), 'workout_attendance', ['plan_day_id'], unique=False)
    op.create_index(op.f('ix_workout_attendance_user_plan_assignment_id'), 'workout_attendance', ['user_plan_assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_attendance_user_plan_assignment_id'), table_name='workout_attendance')
    op.drop_index(op.f('ix_workout_attendance_plan_day_id'), table_name='workout_attendance')
    op.drop_table('workout_attendance')
    op.drop_index(op.f('ix_exercise_assignment_plan_day_id'), table_name='exercise_assignment')
    op.drop_index(op.f('ix_exercise_assignment_exercise_id'), table_name='exercise_assignment')
    op.drop_table('exercise_assignment')
    op.drop_index(op.f('ix_weekly_workout_plan_assignment_weekly_plan_id'), table_name='weekly_workout_plan_assignment')
    op.drop_index(op.f('ix_weekly_workout_plan_assignment_plan_id'), table_name='weekly_workout_plan_assignment')
    op.drop_table('weekly_workout_plan_assignment')
    op.drop_index('uq_one_active_assignment_per_user', table_name='user_plan_assignment', postgresql_where=sa.text("status IN ('in-progress')"))
    op.drop_index(op.f('ix_user_plan_assignment_user_id'), table_name='user_plan_assignment')
    op.drop_index(op.f('ix_user_plan_assignment_plan_id'), table_name='user_plan_assignment')
    op.drop_table('user_plan_assignment')
    op.drop_index(op.f('ix_plan_day_weekly_plan_id'), table_name='plan_day')
    op.drop_index(op.f('ix_plan_day_plan_id'), table_name='plan_day')
    op.drop_table('plan_day')
    op.drop_table('weekly_workout_plan')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_plan_title'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###

    # SQLAlchemy creates these PG ENUM types as a side-effect of the first
    # column that uses them, but drop_table() doesn't tear them down.
    # Dropping them here makes downgrade → upgrade round-trips idempotent.
    op.execute("DROP TYPE IF EXISTS attendancestatus")
    op.execute("DROP TYPE IF EXISTS user_plan_assignment_status")
    op.execute("DROP TYPE IF EXISTS durationtype")
    op.execute("DROP TYPE IF EXISTS equipment")
    op.execute("DROP TYPE IF EXISTS bodycategory")
